n = input('Digite algo: ')
#print('O tipo primitivo desse valor é',type(n))
#print('Só tem espaços?',n.isspace())
#print('É um número?',n.isnumeric())
#print('É alfabético?',n.isalpha())
#print('É alfanumérico?',n.isalnum())
#print('Está em maiúsculas?',n.isupper())
#print('Está em minúsculas?',n.islower())
#print('Está capitalizada?',n.istitle())
n0 = type(n)
n1 = n.isspace()
n2 = n.isnumeric()
n3 = n.isalpha()
n4 = n.isalnum()
n5 = n.isupper()
n6 = n.islower()
n7 = n.istitle()
print('O tipo primitivo desse valor é {}'.format(n0))
print('Só tem espaços? {}'.format(n1))
print('É um número? {}'.format(n2))
print('É alfabético? {}'.format(n3))
print('É alfanumérico? {}'.format(n4))
print('Está em maiúsculas? {}'.format(n5))
print('Está em minúsculas? {}'.format(n6))
print('Está capitalizada? {}'.format(n7))

